# Generated by Django 2.2.16 on 2020-10-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
