# Generated by Django 2.2.16 on 2020-11-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0004_auto_20201030_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
